from enum import Enum


class GDownStates(Enum):
    # single
    FILE_SESSION_CREATED = 1
    FILE_URL_PARSED = 2
    FILE_URL_CONFIRMATION_DONE = 3
    FILE_DOWNLOAD_FAILED = 4
    FILE_INVALID_PUBLIC_LINK = 5
    FILE_RESUMING_DOWNLOAD = 6
    FILE_DOWNLOADING = 7
    FILE_DOWNLOAD_COMPLETED = 8
    # folders
    FOLDER_SESSION_CREATED = 30
    FOLDER_SCANNING = 31
    FOLDER_URL_PARSED = 32
    FOLDER_GET_DIR_STRUCTURE = 33
    FOLDER_DOWNLOAD_ERROR = 34
