---
name: Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: make test PYTEST_ARGS='--numprocesses=auto -m "not network"'
  network:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.10'
      - run: make test PYTEST_ARGS='--numprocesses=auto -m network'
